(deftheme silkworm
  "Created 2017-01-19.")

(custom-theme-set-faces
 'silkworm
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#0073b5"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#a9a9a9"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#a74f31"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#a74f31"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#a9a9a9"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ad4271"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold ((class color) (min-colors 89)) :foreground "#367a7f"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#3b4bab"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#76690b"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#a74f31"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff1276" :background "#d9d1c9"))))
 '(region ((((class color) (min-colors 89)) (:background "#585858" :foreground "#ece3db"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#737373" :background "#c6bfb8"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#d9d1c9" :foreground "#808080"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#c6bfb8"))))
 '(isearch ((((class color) (min-colors 89)) (:bold t :foreground "#ff1276" :background "#c6bfb8"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil) :bold t :foreground "#808080" :background "#d9d1c9"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil :style pressed-button) :foreground "#a74f31" :background "#ece3db" :weight normal))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:bold t :foreground "#ad4271" :background nil))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#367a7f" :box nil :weight bold))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#585858"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#737373"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:bold t :foreground "#367a7f"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#a74f31" :underline t))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ff1276"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#ff1276")))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#656565" :background "#c6bfb8"))))
 '(default ((((class color) (min-colors 89)) (:background "#ece3db" :foreground "#585858")))))

(provide-theme 'silkworm)
